---
- name: Install iptables-persistent
  ansible.builtin.package:
    name: iptables-persistent
    state: present

- name: Template network configuration
  ansible.builtin.template:
    src: interfaces.j2
    dest: /etc/network/interfaces
  notify: "Restart networking"


- name: Template ipv4 rules
  ansible.builtin.template:
    src: rules.v4.j2
    dest: /etc/iptables/rules.v4
  notify: "Restart iptables-persistent"


